config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :sessions, only: [:new, :create, :destroy]

  constraints subdomain: 'api' do
    namespace :api, path: '/', defaults: {format: :json} do
      resources :memories
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :users, only: [:show, :update] do
        resources :memories, only: [:index, :show, :create, :update, :destroy]
      end 
      resources :sessions, only: [:new, :create, :destroy]
    end
  end

  resources :users, only: [:show, :create] 

  resources :home, only: [:index, :show]

  resources :bookmarks, only: [:index, ]

  resources :memories, only: [:show]  

  get '/search', to: "home#show"

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks

  before_create :get_city_and_place_id
  
  mount_uploader :media_url, ImageUploader

  def get_city_and_place_id
    query = "#{self.latitude},#{self.longitude}"
    location = Geocoder.search(query)
    self.city = location.first.city
    self.google_place_id = location.first.data["place_id"]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memories
  has_many :bookmarks
  has_many :bookmarked_memories, through: :bookmarks, class_name: "Memory"

  mount_uploader :profile_photo, ImageUploader


  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/api/bookmarks_controller.rb
module API
  class BookmarksController < ApplicationController
  respond_to :json
  
    def index
      if params[:user_id]
        @bookmarks = Bookmark.where(user_id: params[:user_id])
      elsif params[:user_id] && params[:city]
        @memories = Memory.where(user_id: params[:user_id], city: params[:search])
      else
        @bookmarks = Bookmark.all
      end
      respond_with @bookmarks
    end


    def show
      @bookmark = Bookmark.where(id: params[:id])
      respond_with @bookmark
    end

    def create
      @bookmarks = Bookmark.create(bookmark_params)
      respond_with @bookmarks 
    end

    def update
      @bookmark = Bookmark.find(params[:id])
      @bookmark.update_attributes(bookmark_params)
      respond_with @bookmark 
    end

    def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
      respond_with @bookmark 
    end

    protected

    def bookmark_params
      params.require(:bookmark).permit(:memory_id, :user_id)
    end

  end
end

app/controllers/api/memories_controller.rb
module API
  class MemoriesController < ApplicationController
  respond_to :json

    def index

      if params[:id]
         @memories = Memory.where(id: params[:id])
      elsif params[:user_id] && params[:search]
        @memories = Memory.where(user_id: params[:user_id], city: params[:search])
      elsif params[:user_id] && params[:city]
        @memories = Memory.where(user_id: params[:user_id], city: params[:city])
      elsif params[:user_id]
        @memories = Memory.where(user_id: params[:user_id])
      elsif params[:search]
        if params[:search].blank?
          @memories = Memory.all 
        else
          @memories = Memory.where(city: params[:search])
        end
      else 
        @memories = Memory.all
      end
        respond_with @memories
    end

    def show
      @memory = Memory.find(params[:id])
      respond_with @memory
    end

    def create
      @memory = Memory.create(memory_params)
      respond_with @memory 
    end

    def update
      @memory = Memory.find(params[:id])
      @memory.update_attributes(memory_params)
      respond_with @memory 
    end

    def destroy
      @memory = Memory.find(params[:id])
      @memory.destroy
      respond_with @memory 
    end

    protected

    def memory_params
      params.require(:memory).permit(:user_id, :title, :description, :category, :latitude, :longitude, :city, :google_place_id, :media_url, :created_at, :updated_at)
    end
  end

end

app/controllers/api/users_controller.rb
module API
  class UsersController < ApplicationController
  respond_to :json

    def show
      @user = User.find(params[:id])
      respond_with @user 
    end

    def update
      @user = User.find(params[:id])
      @user.update_attributes(user_params)
      respond_with @user 
    end

    protected

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :website, :twitter, :facebook, :biography, :profile_photo, :image)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, if: :isWebRequest?


  #Code is from Stackoverflow. May want to revisit it. http://stackoverflow.com/questions/23673040/override-the-protect-from-forgery-strategy-in-a-controller 
  def isWebRequest?
    request.subdomains[-1] != 'api' 
  end


protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

    # @current_user ||= User.find(session[:user_id]) if session[:user_id]

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_filter :require_login
  
  def index
    render "index"
  end

  private

    def require_login
      unless current_user
        redirect_to home_path
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render "index"
  end

  def show
    @memories = params[:search]
    render "show"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{user.first_name}!"
      redirect_to root_path
    elsif user.nil
      flash[:error] = "Login failed, but failures are a measure of success in life so try again. Unless you're a hacker, stop now!"
      redirect_to root_path       
    else
      flash[:error] = "Login failed, but failures are a measure of success in life so try again. Unless you're a hacker, stop now!"
      redirect_to root_path 
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Bye!"
    redirect_to root_path
    # redirect_to root_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
# def current_user
#   return unless session[:user_id]
#   @current_user ||= User.find(session[:user_id])
# end
 
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to search_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    respond_with @user 
  end

  def show
    @user = User.find(params[:id])
    render "show"
  end

  protected

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :website, :twitter, :facebook, :biography, :profile_photo, :image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/index.html.erb
<h4 style="text-align:center; font-family:quicksand;">BOOKMARKS</h4>
</br>


<% @user_id = params[:user_id] %>

<script>

  function CallURL(searchTerms){
    var url = "http://api.localhost.com:3000/bookmarks";


    $.ajax({     
      type: "GET",
      url: url,
      data: { user_id: searchTerms },
      contentType: "application/json",
      success: function(json) {
        $.each(json, function(i, item) {        
          searchMemories = item.memory_id;
          MemorySearch(searchMemories);
      });
      },
      // error: function(jqXHR, textStatus, errorThrown) {
      //   console.log(textStatus, errorThrown);
      // }
    });
  }


  function CallCity(searchTerms){
    var url = "http://api.localhost.com:3000/bookmarks";

    $.ajax({     
      type: "GET",
      url: url,
      data: { user_id: searchTerms },
      contentType: "application/json",
      success: function(json) {
        $.each(json, function(i, item) {  
          console.log(item);      
          searchMemories = item.memory_id;
          // MemorySearchWithCities(searchMemories, citySearch);
      });
      },
      // error: function(jqXHR, textStatus, errorThrown) {
      //   console.log(textStatus, errorThrown);
      // }
    });
  }

  function MemorySearchWithCities(searchMemories, citySearch){
    var url = "http://api.localhost.com:3000/memories";
    console.log(citySearch);
    console.log(searchMemories);
   $.ajax({     
      type: "GET",
      url: url,
      data: { id: searchMemories, city: citySearch},
      contentType: "application/json",
      success: function(json) {
        $.each(json, function(i, item) {        
          SearchCallback(json);
        });
      },
      // error: function(jqXHR, textStatus, errorThrown) {
      //   console.log(textStatus, errorThrown);
      // }
    });
  }

  function MemorySearch(searchMemories){
    var url = "http://api.localhost.com:3000/memories";
   $.ajax({     
      type: "GET",
      url: url,
      data: { id: searchMemories},
      contentType: "application/json",
      success: function(json) {
        console.log(json);
        SearchCallback(json);
      },
      // error: function(jqXHR, textStatus, errorThrown) {
      //   console.log(textStatus, errorThrown);
      // }
    });
  }

    function SearchCallback(json) {
    $.each(json, function(i, item) {
      console.log(item);
            
      $('#wrapper').append('<div class="item ' + item.city +'" >' + (moment(item.created_at).format("MMM Do YYYY")) + "<br/><h6>" + item.latitude + ', ' + item.longitude + " | " +(moment(item.created_at).format("h:mm a")) + ' | ' + item.category + '</h6>' + item.description + '</div>'); 
      $('#citynav').append('<li class="citybutton"><a href="#" data-city_id="' + item.city + '" data-filter="' + item.city + '">' + item.city + '</a></li>');


         $("img").error(function(){
           $(this).hide();
           }); 
      });
    };


  $(function() {

    var searchTerms = "<%= @user_id %>";
    CallURL(searchTerms);
  
    var $container = $('#wrapper'); 

    $container.isotope({ 
        filter: '*', 
        animationOptions: { 
            duration: 750, 
            easing: 'linear', 
            queue: false, 
        } 
    }); 


    $('#citynav').on('click','.citybutton', function(e){
      e.preventDefault();
      $('#citynav .current').removeClass('current');
      $(this).addClass('current');

      var selector = $(this).children().data('filter');
      console.log(selector);
      $container.isotope({
        filter: selector,
        animationOptions: {
          duration: 750,
          easing: 'linear',
          queue: false
        }
     });
    });
  });
</script>

<a href="#" class="button citymemories" data-options="align:bottom" data-dropdown="citynav" style="display: block;">CITIES</a>
<ul  id="citynav" class="medium f-dropdown" data-dropdown-content>
  <li class="citybutton current">
    <a href="#" data-city_id="*" data-filter=".*">All</a>
    </li>
</ul>

<br/><br/>


<div id="wrapper">

</div>

app/views/home/index.html.erb
<br><br>
<div id="indeximage">
<div id="searchfields">
<form  id='search-form' action="/search" method="get"> 
  <div class="row">
    <div class="ten mobile-three columns">
      <input id="search-city" class="search-input"type="text" name="search" placeholder="search a city" />
    </div>
    <div class="two mobile-one columns">
      <input id="search-submit" type="submit" value="EXPLORE" class="button secondary" />
    </div>
  </div>
</form><br>
</div>
</div>



  <% @current_user =  User.find(session["user_id"]) %>
  <h2 style="text-align: center; font-family: quicksand;"> CURATED SOUVENIRS </h2>
  <div class="curated_memories">
    <div class="item" >
      <img src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10459875_10203602067325781_6580568833719525755_n.jpg?oh=712992d235ebd0ecc71c65f6b1ee791c&oe=560325CB" /> 
    </div>
    <div class="item" >
      <img src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/10984598_10203602011444384_7427991684964195941_n.jpg?oh=3eb5b4563e9f43674105c7c09703d4bb&oe=5603E517" /> 
    </div>
    <div class="item" >
      <img src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/11295695_10203602127767292_2318642011000696660_n.jpg?oh=d90fa531cc8fd0ed919349d395495d94&oe=55C536A3" /> 
    </div>
  </div>


<script>

  $(function() {

    $("#indeximage").backstretch([
      "https://scontent-sea1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/13399_10203570847985317_3233685133724634096_n.jpg?oh=ff76e942c36ceab1c694e3ee7b8dbf02&oe=5609EAE7",
      "https://scontent-sea1-1.xx.fbcdn.net/hphotos-xat1/v/l/t1.0-9/11148652_10203570847945316_6882202978588279856_n.jpg?oh=e05728bb82b257d7883f53aadd447ffb&oe=55C5AF02", 
      "https://scontent-sea1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/11215058_10203570847905315_9103989941626003325_n.jpg?oh=dd872df363be95a2d6e965bb6292a13e&oe=560AE496"
    ], {duration: 10000, fade: 1000});

  });

</script>

app/views/home/show.html.erb
<% @current_user =  User.find(session["user_id"]) %>
 <script>

  function CallURL(searchTerms){
    var url = "http://api.localhost.com:3000/memories/";

      $.ajax({     
        type: "GET",
        url: url,
        data: { search: searchTerms },
        contentType: "application/json",
        success: function(json) {
          SearchCallback(json);
        },
        // error: function(jqXHR, textStatus, errorThrown) {
        //   console.log(textStatus, errorThrown);
        // }
      });
    }

    function SearchCallback(json) {
    $.each(json, function(i, item) {
            
      $('#wrapper').append('<div class="item" >' + item.city + "</br>" + (moment(item.created_at).format("MMM Do YYYY")) + "<br/><h6>" + item.latitude + ', ' + item.longitude + " | " +(moment(item.created_at).format("h:mm a")) + ' | ' + item.category + '</h6>' + item.description + '<br/> <img src=' + item.media_url + '/>' + '<br/><img name="bookmark-image" data-memory_id="' + item.id + '" data-user_id=<%= @current_user.id %> class="bookmark-image" src="/assets/bookmark.png" /></div>'); 

         $("img").error(function(){
           $(this).hide();
           }); 
      });
    };


  $(function() {

    var firstRefresh = "<%= @memories %>";

    CallURL(firstRefresh);

    $("#search-submit").on('click', function(e) {
      e.preventDefault();
      var testTerm = $("#search-city").val();
      $("#wrapper").empty();
      console.log(testTerm);
      CallURL(testTerm);
      return false
    });


    $("#wrapper").on('click', ".bookmark-image", function() {
      console.log("bookmarked!");
      console.log($(this).attr("data-memory_id"));
      console.log($(this).attr("data-user_id"));

      var url = "http://api.localhost.com:3000/bookmarks/";
      var bookmark = {
        memory_id: $(this).attr("data-memory_id"),
        user_id: $(this).attr("data-user_id"),
      };

      $.ajax({
        type: "POST",
        url: url,
        data: JSON.stringify(bookmark),
        contentType: "application/json",
        success: function() {
          $("#bookmark_user_id").val("");
          $("#bookmark_memory_id").val("");
        }
        // error: function(jqXHR, textStatus, errorThrown) {
        //   console.log(textStatus, errorThrown);

        //   $("#notice-header").text("Give it a sec, and try again!");

        // }
      });
    });

  });


</script>

<form id='search-form'> 
  <div class="row">
    <div class="ten mobile-three columns">
      <input id="search-city" class="search-input"type="text" name="search" placeholder="Search Cities" />
    </div>
    <div class="two mobile-one columns">
      <button id="search-submit" type="button" value="search" class="button expand postfix">SEARCH</button>
    </div>
  </div>
</form>
<h3 style="text-align: center; font-family: quicksand;"> SEARCH RESULTS: </h3></br>
<div id="wrapper">
  <div id="list">
  </div>  
</div>

app/views/layouts/_flash_messages.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
<footer>

  <small>
    <% if current_user %>
      Signed in as <%= current_user.email %>
    <% end %>
  </small>


</footer>
</div>

app/views/layouts/_login.html.erb
<!-- Triggers the modals -->

<!-- Reveal Modals begin -->
<div id="loginModal" class="reveal-modal small" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
  <h2 class="modaldetailsheader">LOGIN</h2>

      <%= form_tag sessions_path do %>
        <div>
          <%= label_tag "email", "EMAIL:", :class => "modal-form-control" %>
          <%= text_field_tag "email" %>
        </div>
        <div>
          <%= label_tag :password, "PASSWORD:", :class => "modal-form-control" %>
          <%= password_field_tag :password %>
        </div>
        <div><%= submit_tag "LOG IN", class: "secondary button submit_login" %></div>
      <% end %>

      <br/>
  <p><a href="#" data-reveal-id="secondModal" class="button new_user">NOT A USER? SIGN UP HERE</a></p>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="secondModal" class="reveal-modal small" data-reveal aria-labelledby="secondModalTitle" aria-hidden="true" role="dialog">
  <h2 class="modaldetailsheader">SIGN UP</h2>
  <p class="modaldetailsheader">USER DETAILS:</p>

  <a class="close-reveal-modal" aria-label="Close">&#215;</a>

  <%= form_for :user, url: users_path, action: "post" do |f| %>

    <div class="modal-form-control">
      <%= f.label :first_name, "FIRST NAME" %>
      <%= f.text_field :first_name %>
    </div>

    <div class="modal-form-control">
      <%= f.label :last_name, "LAST NAME" %>
      <%= f.text_field :last_name %>
    </div>

    <div class="modal-form-control">
      <%= f.label :email, "EMAIL:"%>
      <%= f.text_field :email%>
    </div>

    <div class="modal-form-control">
      <%= f.label :password, "PASSWORD:"%>
      <%= f.password_field :password %>
    </div>

    <div class="modal-form-control">
      <%= f.label :website, "WEBSITE:" %>
      <%= f.text_field :website %>
    </div>

    <div class="modal-form-control">
      <%= f.label :biography, "BIOGRAPHY:" %>
      <%= f.text_field :biography %>
    </div>
<!-- 
    <div class="modal-form-control">
      <%= f.label :profile_photo, "UPLOAD PROFILE PHOTO:" %>
      <%= f.file_field :profile_photo %>
    </div>
 -->
    <div>
    <%= f.submit "SIGN UP" %>
    </div>

  <% end %>
</div>

<!-- Reveal Modals end -->

app/views/layouts/_navbar.html.erb
<div data-magellan-expedition="fixed">
  <div class="row full-width app-bar">

    <div class="text-left small-4 medium-2 columns">
        <ul class="left">
          <a href="#"data-options="align:right" data-dropdown="drop"><img class="menu-image" src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/19694_10203592164238210_1396540413212103091_n.jpg?oh=4e582a85f970d1f8c0dc68ed64292c2c&oe=560972BF" /></a>
          <ul id="drop" class="large f-dropdown" data-dropdown-content>
          
            <li><a href="/">explore</a></li>

            <% if !current_user %>
              <li><a href="#" data-reveal-id="loginModal">Sign In</a></li>
            <% end %>
            
            <% if current_user %>
              <li>   
                <%= link_to "my souvenirs", user_path(current_user)%> 
              </li>
              <li>   
                <%= link_to "my bookmarks", user_bookmarks_path(current_user) %> 
              </li>
              <li>   
                <%= link_to "sign out", session_path(current_user), method: :delete %>

              </li>
            <% end %>

          </ul>
        </ul>
    </div>

    <div class="small-4 medium-8 columns">
      <a href="#" data-dropdown="drop"><img class="logo-image" src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11011840_10203592164438215_2204799397840360914_n.jpg?oh=29cc9c503ec2612c8dec71cb97cc1e91&oe=55F73374" /></a> 
    </div>

    <div class="text-right small-4 medium-2 columns username_display">
      <%# if current_user %>
        <%#= current_user.full_name %> 
      <%# end %>

    <% if current_user %>

      <a href="#" id= "memory_icon" href="#" data-reveal-id="memoryModal"><img class="create-image" src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-xtf1/v/t1.0-9/11118045_10203592177638545_5283787210368737933_n.jpg?oh=2c34434e954adb38bd0f09bc1433298b&oe=55C61D92" /></a>

    <% end %>

    </div>

  </div>

</div>

app/views/layouts/_newmemory.html.erb
<!-- MODAL WINDOW -->    
<% if current_user %>

  <div id="memoryModal" class="reveal-modal medium" data-reveal>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    
    <% @current_user =  User.find(session["user_id"]) %>
    
    <h3 class="modaldetailsheader">Souvenir Details</h3>
    <fieldset>


    <script type="text/javascript"> 

      $(function() {
      
        $("#memory_icon").on('click', function() {
          navigator.geolocation.getCurrentPosition(set_coordinates);


          function set_coordinates(obj) {
            console.log(obj.coords.latitude);
            console.log(obj.coords.longitude);
            $('input#memory_latitude').val(obj.coords.latitude);
            $('input#memory_longitude').val(obj.coords.longitude);
          };
        });

        $("#memory-submit").on('click', function() {

          console.log("click")

          var url = "http://api.localhost.com:3000/users/" + <%=@current_user.id %> + "/memories/";
          var memory = {
            user_id: <%=@current_user.id %>,
            title: $("#memory_title").val(),
            description: $("#memory_description").val(),
            longitude: $("#memory_longitude").val(),
            latitude: $("#memory_latitude").val(), 
            category: $("#memory_category").val(),
            media_url: $("#memory_media_url").val()
          }; 

          $.ajax({     
            type: "POST",
            url: url,
            data: JSON.stringify(memory),
            contentType: "application/json",
            success: function() {
              $("#memory_title").val("");
              $("#memory_description").val("");
              $("#memory_longitude").val("");
              $("#memory_latitude").val("");
              $("#memory_category").val("");
              $("#memory_media_url").val("");
              $("#memoryModal").foundation('reveal', 'close');
            },
            error: function(jqXHR, textStatus, errorThrown) {
              console.log(textStatus, errorThrown);

              $("#notice-header").text("Give it a sec, and try again!");

            }
          });
        });

      });

    </script>

  <div class="memory_create">
    <%= form_for :memory do |f| %>


    <!--   <h4 id= "notice-header">Please enter your Souvenir details:</h4> -->

      <div>
        <%= f.label :title, "TITLE:", class: 'modal-form-control' %>
        <%= f.text_field :title, placeholder: 'Title', class: 'modal-form-control'  %>
      </div>
      <div>
        <%= f.label :description, "DESCRIPTION:", class: 'modal-form-control' %>
        <%= f.text_field :description, placeholder: 'Description', class: 'modal-form-control' %>
      </div>
      <div>
        <%= f.label :category, "CATEGORY:", class: 'modal-form-control' %>
        <%= f.text_field :category, placeholder: 'Category', class: 'modal-form-control' %>
      </div>
      <div>
        <%= f.label :media_url, "UPLOAD AN IMAGE:", class: 'modal-form-control' %>
        <%= f.file_field :media_url, class: 'modal-form-control' %>
      </div>
        <%= f.hidden_field :longitude %>
        <%= f.hidden_field :latitude %>
        <%= f.hidden_field :city %>
        <%= f.hidden_field :google_place_id %>
        <% @current_user =  User.find(session["user_id"]) %>
       <div>
       <button id="memory-submit" class="secondary button" type="button">Save</button>
       </div>
    <% end %>
  </div>

<% end %>
<!-- MODAL WINDOW END --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Quicksand">
    <meta charset="utf-8" />

    <link href='https://fonts.googleapis.com/css?family=Raleway|Open+Sans' rel='stylesheet' type='text/css'>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Souvenir" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <%= render "layouts/navbar" %>


    <%= render 'layouts/flash_messages' if !flash.empty? %>
    <%= flash[:error] %>

    <%= yield %>

    <%= render "layouts/footer" %>

    <%= render "layouts/newmemory" %>

    <%= render "layouts/login" %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.0/isotope.pkgd.js"></script>
    <script src="http://momentjs.com/downloads/moment.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>

  </body>
</html>

app/views/memories/index.html.erb
<h1>Souvenir List</h1>

<div class="memory_list">
  <% @memories.each do |memory|%>

    <div class="memory_block">
      <a href = "/memory/<%=memory.id%>"><h1 class = "memory_block_title" ><%= memory.created_at.strftime("%A, %d %B %Y") %></h1></a>
      <p class = "memory_block_time"><%= memory.latitude %>, <%= memory.longitude %> | <%= memory.created_at.strftime("%I.%M %p") %> | <%= memory.category %></p>
      <h1 class = "memory_block_comment">"<%= memory.description%>"</h1>

    </div>

  <%end%>

</div>

<div class="map_rightdisplay">

  <script src="http://maps.googleapis.com/maps/api/js">
  </script>

  <div id="googleMap" class= "google_map"> 
  </div>


</div>

app/views/users/_memoriestilemenu.html.erb
<div id = "memories-edit-menu">
  
  <a id = "memories-menu" href="#" data-dropdown="hover1" data-options="is_hover:true; hover_timeout:5000">edit menu</a>

  <ul id="hover1" class="f-dropdown" data-dropdown-content>
    <li><a href="#">Edit</a></li>
    <li><a id = "menu-del" href="#">Delete</a></li>
    <li><a href="#">Make Private</a></li>
  </ul>

</div>

<script>

// var ur
// var memory_id = 

$("#hover1 #menu-del").on('click', function() {
  

  // var memory_id = $(this).attr("data-memory-id");
  // console.log(memory_id);

var memory_id = $(this).closest('div.user-view-item');
console.log(memory_id)

  // $.ajax({
  //   type: 





  });




// });


</script>